export const Products = [
    {
        id:1,
        price:599,
        brand:"Roadster",
        gender:"Men",
        size:"XL",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114639/roc8Challenge/Men_T-shirt-1_Roadster_tuhbru.jpg"
    },
    {
        id:2,
        price:499,
        brand:"Roadster",
        gender:"Men",
        size:"S",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114654/roc8Challenge/Men_T-shirt-2_Roadster_ekgdgk.jpg"
    },
    {
        id:3,
        price:449,
        brand:"Roadster",
        gender:"Men",
        size:"M",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114664/roc8Challenge/Men_T-shirt-3_Roadster_hukgse.jpg"
    },
    {
        id:4,
        price:549,
        brand:"HRX",
        gender:"Men",
        size:"XL",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114674/roc8Challenge/Men_T-shirt-4_HRX_gznhhy.jpg"
    },
    {
        id:5,
        price:799,
        brand:"HRX",
        gender:"Men",
        size:"XL",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114683/roc8Challenge/Men_T-shirt-5_HRX_wctx0a.webp"
    },
    {
        id:6,
        price:749,
        brand:"HRX",
        gender:"Men",
        size:"L",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114696/roc8Challenge/Men_T-shirt-6_HRX_cqu2do.webp"
    },
    {
        id:7,
        price:649,
        brand:"WRONG",
        gender:"Men",
        size:"L",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114720/roc8Challenge/Men_T-shirt-7_WRONG_ff7as1.webp"
    },
    {
        id:8,
        price:669,
        brand:"WRONG",
        gender:"Men",
        size:"S",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114730/roc8Challenge/Men_T-shirt-8_WRONG_tqwkzs.webp"
    },
    {
        id:9,
        price:679,
        brand:"WRONG",
        gender:"Men",
        size:"M",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114738/roc8Challenge/Men_T-shirt-9_WRONG_cm2imi.webp"
    },
    {
        id:10,
        price:609,
        brand:"The Dry",
        gender:"Women",
        size:"M",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657123864/roc8Challenge/Women-1_TheDry_lrwh4f.webp"
    },
    {
        id:11,
        price:499,
        brand:"The Dry",
        gender:"Women",
        size:"S",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657123871/roc8Challenge/Women-2_TheDry_k2034s.webp"
    },
    {
        id:12,
        price:499,
        brand:"The Dry",
        gender:"Women",
        size:"L",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657123879/roc8Challenge/Women-3_TheDry_k7fko9.webp"
    },
    {
        id:13,
        price:499,
        brand:"Van Heusen",
        gender:"Women",
        size:"S",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657123888/roc8Challenge/Women-4_Van_Heusen_eifnbs.webp"
    },
    {
        id:14,
        price:799,
        brand:"Van Heusen",
        gender:"Women",
        size:"M",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657123900/roc8Challenge/Women-5_Van_Heusen_vyou48.webp"
    },
    {
        id:15,
        price:899,
        brand:"Van Heusen",
        gender:"Women",
        size:"M",
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657123910/roc8Challenge/Women-6_Van_Heusen_qr65tq.webp"

    }
]